### PR TITLE
Fix transferToken() in SDK

### LINKED ISSUE #217: Cannot transfer LPT from explorer
**Describe the bug (required)**

The transfer LPT button in the explorer does not work.

**Expected behavior (required)**

Entering a valid ETH address and valid LPT amount should submit a transfer transaction.

**To Reproduce (required)**
1. Go to the My Account tab in the explorer
2. Click on the Transfer button in the Livepeer Token Balance card
3. Enter a valid ETH address and valid LPT amount <= your balance
4. See error "addr is not defined"

**Device (required):**
 - Device: Macbook Pro
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by yondonfu**
**What does this pull request do? Explain your changes. (required)**

Fixes the transferToken() function in the SDK.

**Specific updates (required)**

- Skips approval process in transferToken()
- Fixes incorrect variable reference in transferToken()

**How did you test each of these updates (required)**

I ran the explorer locally and tried transferring LPT on Rinkeby.

**Does this pull request close any open issues?**

Fixes #217 

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/sdk/src/index.js [hunk 1]
```diff
@@ -902,19 +902,10 @@ export default async function createLivepeerSDK(
           )} LPT because is it greater than your current balance (${balance} LPT).`,
         )
       }
-      // approve address / amount with LivepeerToken...
-      await utils.getTxReceipt(
```
Comment (yondonfu) [inline packages/sdk/src/index.js:906]: Don't need to submit an approval transaction when transferring LPT to someone from your own account

**Review by Randy1Burrell — APPROVED** [review]
Good to go.
