### PR TITLE
fix(packages/explorer/graphql-sdk/src/resolvers/Mutations.js): Fix un…

### LINKED ISSUE #315: Can't view explorer after declining Metamask login
**Describe the bug (required)**
My Metamask is active but not logged in. When I try to visit the explorer, I cancel the login prompt. All I see on the explorer page is a pink screen.

**Expected behavior (required)**
The explorer should be shown.

**To Reproduce (required)**
1. Activate Metamask, but don't log in
2. Visit https://explorer.livepeer.org/
3. Dismiss the login prompt
4. See a pink screen

**Device (required):**
Chrome OSX

### PR DESCRIPTION
**Pull request by Randy1Burrell**
…defined defaultTX err

**What does this pull request do? Explain your changes. (required)**

Fixes a a bug that causes undefined defaultTx err when unbonding.

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

FIxes #315 and #311 

**Screenshots (optional):**

### Before Giving Permission to MetaMask
image

### After refusing MetaMask Permission
image

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/graphql-sdk/src/resolvers/Mutation.js [hunk 1]
```diff
@@ -160,19 +160,18 @@ export async function unbond(
...
-      ? bondedAmount
-      : pendingStake
+  const { amount } = args
+  let gas = 0
+  try {
+    gas = await ctx.livepeer.rpc.estimateGas('BondingManager', 'unbond', [
+      amount,
+    ])
+  } catch (err) {
+    console.log(err)
```
Comment (yondonfu) [inline packages/graphql-sdk/src/resolvers/Mutation.js]: I think that if `estimateGas()` throws an error we will continue and try submitting a transaction with 0 gas which would always fail - perhaps we should prevent transaction submission in this case.

File: packages/explorer/src/components/ClaimEarningsForm/index.js [hunk 2]
```diff
@@ -79,14 +65,13 @@ const ClaimEarningsForm: React.ComponentType<ClaimEarningsFormProps> = ({
...
-    // console.log('rendering claimEarnings success')
     return (
       <React.Fragment>
-        {confetti}
+        <Confetti active={submitSucceeded} />
         <p>
           Congratulations! You successfully claimed your earnings through round
-          #{endRound}. You now have {remaining} rounds of earnings left to
-          claim.
+          #{endRound}. You now have {Math.abs(remaining)} rounds of earnings
```
Comment (yondonfu) [inline packages/explorer/src/components/ClaimEarningsForm/index.js]: Has it ever been the case where `remaining` is negative? If so, I think something somewhere else is going wrong i.e. allowing someone to try to claim earnings for more rounds than should be possible and that the problem should be resolved there. Otherwise, if `remaining` is indeed negative here, then the user is still shown inaccurate information i.e. taking the absolute value of a negative # of rounds claimed which wouldn't make sense.

File: packages/explorer/src/components/ClaimEarningsForm/index.js [hunk 3]
```diff
@@ -100,11 +85,11 @@ const ClaimEarningsForm: React.ComponentType<ClaimEarningsFormProps> = ({
   }
   return (
     <React.Fragment>
-      {confetti}
       {max === '20' && (
         <InlineHint flag="claim-earnings-max" disableHide>
           <p>
-            <strong>Note:</strong> You may claim up to 20 rounds at a time.
+            <strong>Note:</strong> You may claim up to {maxEarningsClaimsRounds}{' '}
```
Comment (yondonfu) [inline packages/explorer/src/components/ClaimEarningsForm/index.js:91]: Out of curiosity what does `{' ' }` do? Is it not sufficient to just have `{maxEarningsClaimsRounds} rounds`?

File: packages/explorer/src/components/UnbondTx.js [hunk 4]
```diff
@@ -32,55 +34,60 @@ const UnbondTx = ({
...
+            style={{ fontSize: 12, marginTop: canWithdraw ? '0px' : '-10px' }}
+          >
+            {canWithdraw
+              ? `The unbonding period has completed${
+                  isMe
+                    ? ' and you can withdraw your LPT'
+                    : ' for this amount of LPT'
+                }.`
+              : isMe
+              ? `You will be able to unbond approximately on
```
Comment (yondonfu) [inline packages/explorer/src/components/UnbondTx.js]: Should this be "You will be able to withdraw approximately on..."?

File: packages/explorer/src/components/UnbondTx.js [hunk 5]
```diff
@@ -32,55 +34,60 @@ const UnbondTx = ({
...
+                 ${formatRoundsToDate(withdrawRound - currentRound)}.`
+              : `This amount of LPT can be unbonded on
```
Comment (yondonfu) [inline packages/explorer/src/components/UnbondTx.js]: Should this be "This amount of LPT can be withdraw on..."?

File: packages/explorer/src/components/UnbondingForm/index.js [hunk 6]
```diff
@@ -76,14 +65,15 @@ const UnbondForm: React.StatelessFunctionalComponent<UnbondFormProps> = ({
   if (submitSucceeded) {
     return (
       <React.Fragment>
-        {confetti}
-        <h3>Success: The Unbonding Process Has Begun.</h3>
+        <Confetti active={submitSucceeded} />
+        <H1>Success!</H1>
+        <h3>The Unbonding Process Has Begun.</h3>
         <p>
           It will take 7 days (the unbonding period) in order to be able to
```
Comment (yondonfu) [inline packages/explorer/src/components/UnbondingForm/index.js:72]: Just noting that ideally the unbonding period would be fetched from the contract instead of using a hardcoded number of days since technically the unbonding period could be changed in the future. This can probably be resolved outside of this PR though.

File: packages/explorer/src/enhancers/index.js [hunk 7]
```diff
@@ -538,3 +538,63 @@ export const connectAccountDelegatorUnbondLockQuery = graphql(
...
+    status
+    delegateAddress
+    bondedAmount
+    fees
+    delegatedAmount
+    lastClaimRound
+    pendingFees
+    pendingStake
+    startRound
+    withdrawAmount
```
Comment (yondonfu) [inline packages/explorer/src/enhancers/index.js]: I don't think we need `withdrawAmount` and `withdrawRound` in this query anymore since we can also query for unbonding locks now? These fields were originally included to hide unbonding locks from the user (since a UI for unbonding locks was not available yet)

File: packages/explorer/src/views/AccountOverview/index.js [hunk 8]
```diff
@@ -50,6 +58,15 @@ const AccountOverview: React.ComponentType<AccountOverviewProps> = ({
   const transactionData = transactions.data
     // only livepeer transactions
     .filter(x => x.method)
+
+  if (unbondlocks) {
+    const reducer = (accumulator, itemNext) =>
+      (accumulator = MathBN.add(accumulator, itemNext.amount))
+    const filter = item => item['withdrawRound'] !== '0'
+    unbondlocks = unbondlocks.filter(filter)
+    unbondlocks = unbondlocks.reduce(reducer, 0)
```
Comment (yondonfu) [inline packages/explorer/src/views/AccountOverview/index.js]: This is a little confusing to me as `unbondlocks` initially is an array and then after this reduction it stores a single value - perhaps track the accumulated value in a separate variable for clarity

File: packages/explorer/src/views/AccountOverview/index.js [hunk 9]
```diff
@@ -106,7 +128,32 @@ const AccountOverview: React.ComponentType<AccountOverviewProps> = ({
...
-                <span>bond to a transcoder</span>
+                <span style={{ fontSize: '10px' }}>bond to a transcoder</span>
+                <span style={{ marginLeft: 8 }}>&rarr;</span>
+              </Button>
+            </React.Fragment>
+          )}
+        </MetricBox>
+        <MetricBox
+          className="eth-balance"
+          help={`The amount of Livepeer Token (LPT) owned  owned by this
```
Comment (yondonfu) [inline packages/explorer/src/views/AccountOverview/index.js]: "(LPT) owned  owned" -> "(LPT) owned by"?

File: packages/explorer/src/views/ClaimEarnings/index.js [hunk 10]
```diff
@@ -37,7 +37,8 @@ const ClaimEarningsView: React.ComponentType<ClaimEarningsViewProps> = ({
         from={from}
         initialValues={{ numRounds: '1' }}
         loading={loading}
-        max={MathBN.min(diff, maxClaims)}
+        max={MathBN.min(diff, maxEarningsClaimsRounds)}
+        maxEarningsClaimsRounds={maxEarningsClaimsRounds}
```
Comment (yondonfu) [inline packages/explorer/src/views/ClaimEarnings/index.js:41]: Are the brackets around `maxEarningsClaimsRounds` necessary?

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: packages/explorer/src/views/AccountDelegating/index.js [hunk 11]
```diff
@@ -134,10 +134,13 @@ const AccountDelegating: React.ComponentType<AccountDelegatingProps> = ({
...
                 withdrawAmount,
                 18,
-              )} LPT may be withdrawn at round #${withdrawRound}`
+              )} LPT may be withdraw approximately on ${formatRoundsToDate(
+                withdrawRound - lastInitializedRound,
+              )}`
             : `${formatBalance(withdrawAmount, 18)} LPT may be withdrawn`
         }
       >
+        {console.log(withdrawRound)}
```
Comment (iameli) [inline packages/explorer/src/views/AccountDelegating/index.js]: This is a bit noisy

File: packages/explorer/src/components/ClaimEarningsForm/index.js (hunk 3 above)
Comment (iameli) [reply packages/explorer/src/components/ClaimEarningsForm/index.js:91]: Usually these are introduced by Prettier being overzealous in maintaining the input formatting

File: packages/explorer/src/utils.js [hunk 12]
```diff
@@ -182,14 +189,17 @@ export async function enableAccounts() {
...
   return
 }
 
 export async function limitedMode() {
-  window.limitedWeb3Conn = true
-  window.web3 = new window.Web3(window.ethereum)
+  // Enable limited mode if and only if window.Web3 exists
+  if (window.Web3) {
+    window.limitedWeb3Conn = true
+    window.web3 = new window.Web3(window.ethereum)
```
Comment (iameli) [inline packages/explorer/src/utils.js:200]: I'm not yet familiar with these, but might it ever be the case that `window.Web3` is defined but `window.ethereum` is not? `if (window.Web3 && window.ethereum)`, perhaps?

File: packages/explorer/src/views/AccountOverview/index.js [hunk 13]
```diff
@@ -61,28 +78,33 @@ const AccountOverview: React.ComponentType<AccountOverviewProps> = ({
           className="eth-address"
           help="The Ethereum address representing this account"
           title="ETH Address"
-          width="100%"
-          subvalue={<code style={{ fontSize: 16 }}>{id}</code>}
+          value={
```
Comment (iameli) [inline packages/explorer/src/views/AccountOverview/index.js:82]: I also fixed this in my branch; I'll take that commit out of my PR.

File: packages/graphql-sdk/src/resolvers/Mutation.js (hunk 1 above)
Comment (iameli) [reply packages/graphql-sdk/src/resolvers/Mutation.js]: Could just take out the try/catch entirely and bubble up the error.

File: packages/explorer/src/components/BondForm/index.js [hunk 14]
```diff
@@ -156,21 +150,29 @@ const BondForm: React.StatelessFunctionalComponent<BondFormProps> = ({
...
             <Field
-              name="amount"
               component="input"
-              type="number"
-              min="0"
-              max={max}
               disabled={loading}
+              max={max}
+              maxLength={20}
+              min={noZero ? Math.pow(10, -18).toString() : '0'}
```
Comment (iameli) [inline packages/explorer/src/components/BondForm/index.js:170]: Does this field take a string? It looks like every other field takes a number.

File: packages/explorer/src/views/AccountOverview/index.js [hunk 15]
```diff
@@ -9,38 +10,45 @@ import { Card } from 'rmwc/Card'
...
   coinbase: GraphQLProps<Coinbase>,
+  currentRound: GraphQLProps<Round>,
   history: History,
   match: Match,
   onDepositETH: (e: Event) => void,
   onRequestETH: (e: Event) => void,
   onRequestLPT: (e: Event) => void,
   onTransferLPT: (e: Event) => void,
   transactions: GraphQLProps<Transaction>,
+  unbondlocks: GraphQLProps<UnbondLock>,
```
Comment (iameli) [inline packages/explorer/src/views/AccountOverview/index.js:36]: Perhaps camelcase'd `unbondLocks` for consistency?

File: packages/explorer/src/views/AccountOverview/index.js [hunk 16]
```diff
@@ -50,6 +58,15 @@ const AccountOverview: React.ComponentType<AccountOverviewProps> = ({
   const transactionData = transactions.data
     // only livepeer transactions
     .filter(x => x.method)
+
+  if (unbondlocks) {
+    const reducer = (accumulator, itemNext) =>
+      (accumulator = MathBN.add(accumulator, itemNext.amount))
```
Comment (iameli) [inline packages/explorer/src/views/AccountOverview/index.js]: I don't believe the `accumulator =` assignment is necessary here, `MathBN.add` is already returning the value you want

File: packages/explorer/src/components/MetricBox.js [hunk 17]
```diff
@@ -58,6 +59,7 @@ const MetricBox = ({
               textOverflow: 'ellipsis',
               overflow: 'hidden',
               whiteSpace: 'nowrap',
+              fontSize: valueSize || '1.17em',
```
Comment (iameli) [inline packages/explorer/src/components/MetricBox.js]: Another way to handle this would be to pass a `textStyle` prop to `MetricBox` and deconstruct it at the end of this `style`:

```
<strong
  style={{
    fontWeight: 400,
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    fontSize: '1.17em',
    ...(textStyle || {})
  }}
>
```

And invoke with:
```
<MetricBox textStyle={{fontSize: "100px"}} />
```

That'll allow for more customization in the future without adding more props

File: packages/explorer/src/components/UnbondTx.js [hunk 18]
```diff
@@ -32,55 +34,60 @@ const UnbondTx = ({
...
-          justifyContent: 'flex-start',
-        }}
-      >
-        {withdrawRound <= currentRound ? (
-          <Tooltip text="You can withdraw now">
+      {isMe && (
+        <div
+          style={{
+            minWidth: '40%',
+            justifyContent: 'flex-start',
```
Comment (iameli) [inline packages/explorer/src/components/UnbondTx.js:59]: I don't believe this will have an effect unless there's a `display: flex` on the box (I know this wasn't your change though)

File: packages/explorer/src/views/ClaimEarnings/index.js (hunk 10 above)
Comment (iameli) [reply packages/explorer/src/views/ClaimEarnings/index.js:41]: Yeah, it'd put that name in there as a string otherwise

**Review by iameli — CHANGES_REQUESTED** [review]

File: packages/explorer/src/components/ClaimEarningsForm/index.js (hunk 2 above)
Comment (Randy1Burrell) [reply packages/explorer/src/components/ClaimEarningsForm/index.js]: Yes it has been a case where remaining is negative, and sure there is something wrong somewhere. I have found it to say I have -30 unclaimed rounds when I actually have 30 unclaimed rounds. This Math.abs I'll remove until someone is able to find the actual bug.

File: packages/explorer/src/components/UnbondingForm/index.js (hunk 6 above)
Comment (Randy1Burrell) [reply packages/explorer/src/components/UnbondingForm/index.js:72]: Sure let's resolve this in another PR.

File: packages/explorer/src/views/AccountDelegating/index.js (hunk 11 above)
Comment (Randy1Burrell) [reply packages/explorer/src/views/AccountDelegating/index.js]: My mistake. I should have removed this when I was cleaning up the code. I guess I missed it, removing it now.

File: packages/explorer/src/utils.js (hunk 12 above)
Comment (Randy1Burrell) [reply packages/explorer/src/utils.js:200]: @iameli thanks. I've add this in for good measure in case someone screws up and forget to inject ethereum along with web3, but to answer your question MetaMask usually injects both Web3 and ethereum into the window object.

File: packages/explorer/src/views/AccountOverview/index.js (hunk 15 above)
Comment (Randy1Burrell) [reply packages/explorer/src/views/AccountOverview/index.js:36]: @iameli UnbondLock is Pascal Cased for consistency with the rest of the src files in the explorer. Notice how line 35 `Transaction` is Pascal case.

Comment (Randy1Burrell) [reply packages/explorer/src/views/AccountOverview/index.js:36]: @iameli My bad, I thought you meant camel casing the `UnbondLock` prop for GraphQL. Changing it in this area means I will have to change other areas that have already been merged. It's probably best not to touch any other area yet, being that I'm on a tight deadline.

File: packages/explorer/src/components/MetricBox.js (hunk 17 above)
Comment (Randy1Burrell) [reply packages/explorer/src/components/MetricBox.js]: Great suggestion! I have implemented this.

File: packages/explorer/src/components/UnbondTx.js (hunk 18 above)
Comment (Randy1Burrell) [reply packages/explorer/src/components/UnbondTx.js:59]: @iameli Thanks for the review. Implemented!

**Comment by Randy1Burrell** [comment]
@yondonfu and @iameli changes have been implemented.

**Comment by iameli** [comment]
LGTM! 🚢

**Review by yondonfu — APPROVED** [review]
LGTM
