### PR TITLE
Protocol Paused

### LINKED ISSUE #97: Dynamically detect protocol is paused, and put up "protocol paused" modal
**What's the problem? (required)**
Currently the protocol explorer doesn't know when the protocol is paused.  When users use the explorer during protocol pause, all transactions fail.

**What's the current behavior? (required)**
Not able to detect paused protocol

**Describe a possible solution you've considered (optional)**
Protocol explorer can detect when the protocol is paused, warn users, and stop them from doing actions that will trigger a transaction.

### PR DESCRIPTION
**Pull request by ericxtang**
**What does this pull request do? Explain your changes. (required)**
Add a check for protocol paused status, and put up a modal if it's paused.  

**Specific updates (required)**

* Add an API call to get protocol status
* Add graphql schema and query to get the status
* Add a view for the modal

**How did you test each of these updates (required)**
Used mockProtocol to turn on/off the modal

**Does this pull request close any open issues?**
Closes https://github.com/livepeer/livepeerjs/issues/97

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: packages/explorer/src/views/ImportantMessage/index.js [hunk 1]
```diff
@@ -1,18 +1,21 @@
...
-        href="https://forum.livepeer.org/t/protocol-paused-for-bug-fix-upgrade-5-26-18-9-00pm-edt/265"
-        target="_blank"
-      >
-        forum post
-      </a>
-    </p>
-  </BasicModal>
-)
+const ImportantMessage = ({ protocol }) => {
+  console.log('Protocol paused: ' + protocol.data.paused)
```
Comment (jozanza) [inline packages/explorer/src/views/ImportantMessage/index.js]: Let's remove this

File: packages/graphql-sdk/src/types/Protocol.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+const Protocol = `
+    type Protocol {
+        "Protocol paused"
+        paused: Boolean!
+
+        "Protocol id"
+        id: String!
+    }
```
Comment (jozanza) [inline packages/graphql-sdk/src/types/Protocol.js]: The formatting in this block is using 3 or 4 space indents. Let's make sure this type def is using 2 spaces for indentation. It would be helpful to add a comment on the line above the type declaration as well.

**Review by jozanza — CHANGES_REQUESTED** [review]
Looks really good. I think we'll just want to add a couple tests to cover these updates. We need to

- [ ] Add a couple unit tests in `packages/graphql-sdk/src/resolvers/Protocol.test.js` for testing the Protocol type's resolvers.
- [ ] Add a snapshot test in `packages/graphql-sdk/src/index.test.js` for "ProtocolQuery"

The snapshot test will probably look something like this:
```js
/**
 * Account
 */
test('ProtocolQuery', async t => {
  const res = await graphql(schema, ProtocolQuery, null, { livepeer }, {})
  t.snapshot(res)
})
```
You'll need to also add a `getProtocolPaused()` method somewhere in the `rpc` namespace of the mock-sdk (`packages/graphql-sdk/src/mock-sdk.js`)

And last, since you added a new method to the sdk, we should update the generated documentation. Just run `yarn docs` from the project root and add/commit all the updated files.
